version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - "/Users/mfitz/Downloads/VMRMEMBERS.FDB:/firebird/data/VMRMEMBERS.FDB"
    ports:
      - "3050:3050"

