name: Release

on:
  push:
    tags:
      - v*

env:
  WIN64BIN: vmrsync-win64
  TAG: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Windows Version
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o ${{ env.WIN64BIN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          draft: false
          prerelease: false

      - name: Upload release to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.WIN64BIN }}
          asset_name: ${{ env.WIN64BIN }}
          asset_content_type: application/octet-stream

