name: Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: ./test.sh integration

      - name: Check Windows Service build
        working-directory: ./src
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -tags service

